### PR TITLE
LPS-106634 Repositioning app

### PR DESCRIPTION
**Pull request by andresfulla**

### CODE REVIEW

**Comment by andresfulla** [comment]
ci:test:sf

**Comment by andresfulla** [comment]
ci:test:sf

**Comment by dgarciasarai** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by dgarciasarai** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/84797. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
