### PR TITLE
LPS 112296 Added AC disconnection to the teardown

### PR DESCRIPTION
**Pull request by CarlosBrichete**

### CODE REVIEW

**Comment by CarlosBrichete** [comment]
ci:test:tango-analytics-cloud

**Comment by CarlosBrichete** [comment]
ci:test:sf

**Comment by dgarciasarai** [comment]
🍀🚀

**Comment by dgarciasarai** [comment]
ci:stop

**Comment by dgarciasarai** [comment]
ci:stop

**Comment by dgarciasarai** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by dgarciasarai** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by dgarciasarai** [comment]
Pull request submitted to https://github.com/dgarciasarai/liferay-portal/pull/231. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
