### PR TITLE
LPS-110903 Fix css custom properties of color for alert component

### PR DESCRIPTION
**Pull request by eduardoallegrini**
/cc @jbalsas @marcoscv-work

### CODE REVIEW

**Comment by dgarciasarai** [comment]
ci:test:sf

**Comment by dgarciasarai** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by dgarciasarai** [comment]
LGTM 🚀 

Screenshot 2020-03-26 at 11 48 51
Screenshot 2020-03-26 at 11 48 59
Screenshot 2020-03-26 at 11 49 37

**Comment by dgarciasarai** [comment]
ci:forward

**Comment by dgarciasarai** [comment]
ci:test:relevant

**Comment by jpince** [comment]
@xbrianlee
```
     [java] 2020-03-26 11:54:06.588 ERROR [liferay/background_task-2][BackgroundTaskMessageListener:182] Unable to execute background task
     [java] java.lang.IllegalStateException: Future got interrupted
     [java] 	at org.elasticsearch.common.util.concurrent.FutureUtils.get(FutureUtils.java:60)
     [java] 	at org.elasticsearch.action.support.AdapterActionFuture.actionGet(AdapterActionFuture.java:34)
     [java] 	at org.elasticsearch.action.ActionRequestBuilder.get(ActionRequestBuilder.java:53)
     [java] 	at com.liferay.portal.search.elasticsearch6.internal.search.engine.adapter.index.CreateIndexRequestExecutorImpl.execute(CreateIndexRequestExecutorImpl.java:41)
     [java] 	at com.liferay.portal.search.elasticsearch6.internal.search.engine.adapter.index.ElasticsearchIndexRequestExecutor.executeIndexRequest(ElasticsearchIndexRequestExecutor.java:75)
     [java] 	at com.liferay.portal.search.engine.adapter.index.CreateIndexRequest.accept(CreateIndexRequest.java:33)
     [java] 	at com.liferay.portal.search.engine.adapter.index.CreateIndexRequest.accept(CreateIndexRequest.java:22)
     [java] 	at com.liferay.portal.search.elasticsearch6.internal.search.engine.adapter.ElasticsearchSearchEngineAdapterImpl.execute(ElasticsearchSearchEngineAdapterImpl.java:85)
     [java] 	at com.liferay.portal.search.tuning.rankings.web.internal.index.RankingIndexCreatorImpl.create(RankingIndexCreatorImpl.java:43)
```
https://test-1-8.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=0,label_exp=!master/339445/consoleText

**Comment by dgarciasarai** [comment]
ci:forward

**Pull request closed without merging**
