### PR TITLE
LPS-112296 Poshi test connection DXP-AC locally and in CI

### PR DESCRIPTION
**Pull request by dgarciasarai**
This is a huge step to create more end to end tests DXP-AC 🚀 

See PASSED Poshi test here: https://testray.liferay.com/home/-/testray/case_results?testrayBuildId=1171538479&testrayRunId=1171538488

For now just:
- `LocalFile.CreateABTest#CreateABTestRunWithNoVariants`

We have two more ignored and we have to fix it locally first.

### CODE REVIEW

**Comment by dgarciasarai** [comment]
ci:test:sf

**Comment by CarlosBrichete** [comment]
ci:test:tango-analytics-cloud

**Comment by dgarciasarai** [comment]
ci:test:sf

**Comment by dgarciasarai** [comment]
ci:test:tango-analytics-cloud

**Comment by dgarciasarai** [comment]
ci:test:relevant

**Comment by dgarciasarai** [comment]
ci:forward

**Comment by dgarciasarai** [comment]
ci:forward

**Comment by dgarciasarai** [comment]
ci:stop

**Comment by dgarciasarai** [comment]
ci:forward

**Comment by dgarciasarai** [comment]
ci:test:sf

**Comment by dgarciasarai** [comment]
ci:test:tango-analytics-cloud

**Comment by dgarciasarai** [comment]
ci:test:relevant

**Comment by dgarciasarai** [comment]
ci:forward

**Pull request closed without merging**
