### PR TITLE
LPS-112934 Avoid using external variables inside selectors

### PR DESCRIPTION
**Pull request by p2kmgcl**

### CODE REVIEW

**Comment by dgarciasarai** [comment]
ci:test:sf

**Comment by dgarciasarai** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by dgarciasarai** [comment]
ci:test:relevant

**Comment by p2kmgcl** [comment]
> ci:forward

:crossed_fingers: :candle:

**Comment by dgarciasarai** [comment]
ci:test:relevant

**Comment by dgarciasarai** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by dgarciasarai** [comment]
Pull request submitted to https://github.com/dgarciasarai/liferay-portal/pull/225. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
