### PR TITLE
LPS-113658 Fix tests.

### PR DESCRIPTION
**Pull request by cgoncas**

### CODE REVIEW

**Comment by cgoncas** [comment]
ci:test:sf

**Comment by cgoncas** [comment]
ci:test:relevant

**Comment by dgarciasarai** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by dgarciasarai** [comment]
Pull request submitted to https://github.com/dgarciasarai/liferay-portal/pull/234. [See changes here.](https://github.com/dgarciasarai/liferay-portal/compare/04ab8a545e8820~5...04ab8a545e8820) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
