### PR TITLE
LPS-111595 Check if there is a valid connection to AC and show an alert if not

### PR DESCRIPTION
**Pull request by darquesdev**
This is only the frontend side. The backend side is still in development to replace the hardcoded `true` with the real value.

### CODE REVIEW

**Comment by darquesdev** [comment]
ci:forward

**Comment by dgarciasarai** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by dgarciasarai** [comment]
https://github.com/dgarciasarai/liferay-portal/pull/199

**Comment by dgarciasarai** [comment]
Pull request submitted to https://github.com/dgarciasarai/liferay-portal/pull/200. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by dgarciasarai** [comment]
Pull request submitted to https://github.com/darquesdev/liferay-portal/pull/135. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
