### PR TITLE
LPS-116539 Possible fix for "value" collisions

### PR DESCRIPTION
**Pull request by wincent**
@dgarciasarai: I think this might work? See [the commit](https://github.com/dgarciasarai/liferay-portal/commit/34a1aadabb282ba55f5ac804ec8246a19c2e039a) on top of [your PR](https://github.com/liferay-frontend/liferay-portal/pull/80) (also, it's rebased, but that shouldn't make any difference.

1. No stages: `tooltip` is "value", array is length 1, `payload[0].vocabularyName` is set; we want to use `label` (ie. "Some human readable audience") as opposed to `payload[i].name` (ie. "value").
2. One or more stages: array length is 1 or more, but this time `payload[i].name` has a reasonable value (eg. "Some human readable stage"); `payload[i].vocabularyName` is not set.

This seems less likely to collide than `value` might, as per [our comment thread](https://github.com/liferay-frontend/liferay-portal/pull/80#discussion_r450773248).

## Previous PR description:

**Description**

The main goal of this pull request is to show the total number of contents when hovering on a bar

**Feature flag: YES**

The Audit Graph is hidden. The configuration file to show the chart is here: https://issues.liferay.com/browse/LPS-115805

**Module**

```
~/liferay-portal/modules/apps/content-dashboard/content-dashboard-web
```

**Screenshots**

Screenshot 2020-07-07 at 12 01 08

Screenshot 2020-07-07 at 17 20 20

cc: @bryceosterhaus @wincent @eduardoallegrini

### CODE REVIEW

**Comment by wincent** [comment]
ci:test:sf

**Comment by wincent** [comment]
ci:test:relevant

**Comment by dgarciasarai** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by dgarciasarai** [comment]
@wincent this possible fix is actually working fine. Thank you so much 😄 
I'll wait for the CI and close the other PR. I will forward from here if that's ok with you.

**Comment by dgarciasarai** [comment]
ci:forward

**Pull request closed without merging**
