### PR TITLE
LPS-115533 Add clayui/css as a dependency

### PR DESCRIPTION
**Pull request by dgarciasarai**

### CODE REVIEW

**Comment by dgarciasarai** [comment]
cc: @jbalsas @wincent

**Comment by dgarciasarai** [comment]
ci:test:sf

**Comment by dgarciasarai** [comment]
ci:test:tango

**Comment by dgarciasarai** [comment]
ci:forward

**Comment by dgarciasarai** [comment]
@carlosbrichete ☝

**Comment by jbalsas** [comment]
I don't think this makes sense to forward as is... something smells rotten in Denmark

**Comment by dgarciasarai** [comment]
ci:stop

**Comment by dgarciasarai** [comment]
I closed https://github.com/brianchandotcom/liferay-portal/pull/90218. I'll fix this in another PR.

**Comment by dgarciasarai** [comment]
See https://github.com/dgarciasarai/liferay-portal/pull/250

**Pull request closed without merging**
