### PR TITLE
LPS-116288 Add info panel to Content Dashboard

### PR DESCRIPTION
**Pull request by cgoncas**
Hey @dgarciasarai!!

This pull adds support for info panel in the Content Dashboard, I have followed the same pattern found in Wiki, after a talk with Susana, please, take a look so we could fix the looks of the Info Panel.

Thanks!!

### CODE REVIEW

**Comment by cgoncas** [comment]
ci:test:sf

**Comment by cgoncas** [comment]
ci:test:relevant

**Comment by dgarciasarai** [comment]
ci:test:relevant

**Comment by dgarciasarai** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by dgarciasarai** [comment]
https://github.com/cgoncas/liferay-portal/pull/553

**Pull request closed without merging**
