### PR TITLE
LPS-110922 Update liferay-ckeditor to v4.13.1-liferay.4

### PR DESCRIPTION
**Pull request by julien**

### CODE REVIEW

**Comment by julien** [comment]
ci:test:sf

**Comment by dgarciasarai** [comment]
ci:test:sf

**Comment by dgarciasarai** [comment]
ci:test:relevant

**Comment by dgarciasarai** [comment]
ci:test:relevant

**Comment by jpince** [comment]
ci:stop added https://github.com/julien/liferay-portal/pull/248 to [the doc](https://docs.google.com/document/d/1HO44sGFIT1r_8Wa4ozoyaxWgdZ4jcM9JeWXqZwuaTws/edit) instead

**Comment by jpince** [comment]
ci:close

**Comment by dgarciasarai** [comment]
Thanks @jpince :) 
/cc @julien

**Pull request closed without merging**
