### PR TITLE
LPS-111428 Test Chart and Navigation components

### PR DESCRIPTION
**Pull request by dgarciasarai**
Testing:
* **Chart:** Message 'No data is available yet.'
* **Navigation:** Alert error 'An unexpected error occurred.'
* **Navigation:** Alert warning 'Some data is temporarily unavailable'

@wincent resending...
https://github.com/brianchandotcom/liferay-portal/pull/88041#issuecomment-620044997

### CODE REVIEW

**Comment by dgarciasarai** [comment]
ci:test:sf

**Comment by dgarciasarai** [comment]
ci:test:sf

**Comment by dgarciasarai** [comment]
ci:test:relevant

**Comment by dgarciasarai** [comment]
ci:forward

**Comment by wincent** [comment]
> @wincent resending...

Sorry about the churn. I expect the conflict was probably due to a big Prettier update (to v2) that went in last night and touched a lot of files.

**Pull request closed without merging**
