### PR TITLE
LPS-115046 Responsive EmptyBarChart

### PR DESCRIPTION
**Pull request by dgarciasarai**
On top of https://github.com/bryceosterhaus/liferay-portal/pull/70

### CODE REVIEW

**Comment by dgarciasarai** [comment]
ci:test:sf

**Comment by dgarciasarai** [comment]
ci:test:relevant

**Comment by dgarciasarai** [comment]
Screenshot 2020-06-08 at 17 56 25
Screenshot 2020-06-08 at 17 56 39

**Comment by bryceosterhaus** [comment]
Looks good to me!

**Comment by bryceosterhaus** [comment]
ci:forward

**Pull request closed without merging**
