### PR TITLE
LPS-108860 Traffic sources

### PR DESCRIPTION
**Pull request by dgarciasarai**

### CODE REVIEW

**Comment by dgarciasarai** [comment]
ci:test:sf

**Comment by dgarciasarai** [comment]
ci:test:relevant

**Comment by dgarciasarai** [comment]
The failing tests are not related with this PR:
```
Test Result (8 failures / +8)
com.liferay.poshi.runner.PoshiRunner.test[LocalFile.ContentPagesWithFragmentConfiguration#AddTextConfigurationFragmentToContentPage]
com.liferay.poshi.runner.PoshiRunner.test[LocalFile.ContentPagesWithFragmentConfiguration#RestoreAndChangeConfigurationFragmentToContentPage]
com.liferay.poshi.runner.PoshiRunner.test[LocalFile.ContentPagesWithSearch#FilterByPageFacet]
com.liferay.poshi.runner.PoshiRunner.test[LocalFile.ContentPageTemplatesWithFragmentConfiguration#AddCheckboxConfigurationFragmentToContentPageTemplate]
com.liferay.poshi.runner.PoshiRunner.test[LocalFile.ContentPagesWithEditables#AddContentPageWithHTMLFragment]
com.liferay.poshi.runner.PoshiRunner.test[LocalFile.ContentPagesWithFragmentConfiguration#ActivateFragmentConfigurationViaTopper]
com.liferay.poshi.runner.PoshiRunner.test[LocalFile.ContentPagesWithFragmentConfiguration#AddCheckboxConfigurationFragmentToContentPage]
com.liferay.poshi.runner.PoshiRunner.test[LocalFile.ContentPagesWithFragmentConfiguration#AddSelectConfigurationFragmentToContentPage]
```

**Comment by brianchandotcom** [comment]
@dgarciasarai can you kindly bug someone from QA in Spain to ignore or fix:

```
Test Result (8 failures / +8)
com.liferay.poshi.runner.PoshiRunner.test[LocalFile.ContentPagesWithFragmentConfiguration#AddTextConfigurationFragmentToContentPage]
com.liferay.poshi.runner.PoshiRunner.test[LocalFile.ContentPagesWithFragmentConfiguration#RestoreAndChangeConfigurationFragmentToContentPage]
com.liferay.poshi.runner.PoshiRunner.test[LocalFile.ContentPagesWithSearch#FilterByPageFacet]
com.liferay.poshi.runner.PoshiRunner.test[LocalFile.ContentPageTemplatesWithFragmentConfiguration#AddCheckboxConfigurationFragmentToContentPageTemplate]
com.liferay.poshi.runner.PoshiRunner.test[LocalFile.ContentPagesWithEditables#AddContentPageWithHTMLFragment]
com.liferay.poshi.runner.PoshiRunner.test[LocalFile.ContentPagesWithFragmentConfiguration#ActivateFragmentConfigurationViaTopper]
com.liferay.poshi.runner.PoshiRunner.test[LocalFile.ContentPagesWithFragmentConfiguration#AddCheckboxConfigurationFragmentToContentPage]
com.liferay.poshi.runner.PoshiRunner.test[LocalFile.ContentPagesWithFragm
```

**Pull request closed without merging**
