### PR TITLE
LPS-112304 Test it

### PR DESCRIPTION
**Pull request by cgoncas**

### CODE REVIEW

**Comment by cgoncas** [comment]
ci:test:sf

**Comment by cgoncas** [comment]
ci:test:relevant

**Comment by dgarciasarai** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by dgarciasarai** [comment]
ci:test:relevant

**Comment by dgarciasarai** [comment]
Pull request submitted to https://github.com/dgarciasarai/liferay-portal/pull/209. [See changes here.](https://github.com/dgarciasarai/liferay-portal/compare/29bbe04b4eae6e~6...29bbe04b4eae6e) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
